### PR TITLE
add ensure => template property

### PR DESCRIPTION
**Pull request by igalic**
this property allows us to create template jails which then can be
cloned.

The WIP is because i don't know how to go about `create`,  and it needs
tests and documentation.

### CODE REVIEW

**Comment by xaque208** [comment]
This is looking good to me @igalic.  Thank you for putting in the work!

**Comment by igalic** [comment]
i declare this to be done

**Comment by igalic** [comment]
n.b.: i'll be basing my next pr on this work

**Comment by xaque208** [comment]
Appreciate the tests!

**Pull request merged**
